version: '3.8'

services:
  mongodb:
    container_name: "mongodb"
    image: mongo
    ports:
      - "10.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_DATABASE: IoT_network
      MONGO_USER_USERNAME_FILE: /run/secrets/mongodb_user_username
      MONGO_USER_PASSWORD_FILE: /run/secrets/mongodb_user_password
      MONGO_GATHERER_USERNAME_FILE: /run/secrets/mongodb_gatherer_username
      MONGO_GATHERER_PASSWORD_FILE: /run/secrets/mongodb_gatherer_password
    secrets:
      - mongodb_root_password
      - mongodb_root_username
      - mongodb_user_username
      - mongodb_user_password
      - mongodb_gatherer_username
      - mongodb_gatherer_password
    volumes:
      - ./mongo_init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - database:/data/db

secrets:
  mongodb_root_password:
    file: ./secrets/.mongodb_root_password
  mongodb_root_username:
    file: ./secrets/.mongodb_root_username
  mongodb_user_password:
    file: ./secrets/.mongodb_user_password
  mongodb_user_username:
    file: ./secrets/.mongodb_user_username
  mongodb_gatherer_password:
    file: ./secrets/.mongodb_gatherer_password
  mongodb_gatherer_username:
    file: ./secrets/.mongodb_gatherer_username

volumes:
  database: