#define WIFI_SSID ""
#define WIFI_PASSWORD ""

#define MQTT_BROKER_IP "10.0.0.1"
#define MQTT_BROKER_PORT 1234


#define WIREGUARD_LOCAL_PRIVATE_KEY "SGpW8eVmtoyPn/qhjRYwoRau6Z0PfyC5jetjmh/mEUA="
#define WIREGUARD_REMOTE_PUBLIC_KEY "l8VxWYQHad3Ex5EdsiJxxMfKaybkND3FO1EBQKZ451I="
#define WIREGUARD_LOCAL_ADDRESS "10.0.0.2"
#define WIREGUARD_ENDPOINT_ADDRESS "192.168.123.110"
#define WIREGUARD_ENDPOINT_PORT 51820

#define UNI_IDENTITY 
